#!/usr/bin/env python3
"""Generate Markdown model docs from source docstrings and config fields."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODELS_DIR = ROOT / "src" / "zynamics" / "models"
MODEL_DOCS_DIR = ROOT / "docs" / "models"
GENERATED_NOTICE = "<!-- Generated by scripts/generate_model_docs.py. Do not edit manually. -->"


@dataclass(frozen=True)
class ConfigField:
    name: str
    annotation: str
    default: str


@dataclass(frozen=True)
class ModelDoc:
    model_name: str
    model_class: str
    model_module: str
    model_docstring: str
    config_class: str
    config_module: str
    config_docstring: str
    config_fields: tuple[ConfigField, ...]
    source_path: Path

    @property
    def page_name(self) -> str:
        return f"{self.model_name}.md"

    @property
    def summary(self) -> str:
        return _first_paragraph(self.model_docstring)

    @property
    def details(self) -> str:
        return _remaining_docstring(self.model_docstring)


class ModelDocError(RuntimeError):
    """Raised when model docs cannot be generated from source."""


def discover_models(root: Path = ROOT) -> list[ModelDoc]:
    """Discover registered model configs and their target model classes."""

    models_dir = root / "src" / "zynamics" / "models"
    docs: list[ModelDoc] = []

    for path in sorted(models_dir.glob("*.py")):
        if path.name in {"__init__.py", "base.py"}:
            continue
        source = path.read_text(encoding="utf-8")
        module = ast.parse(source, filename=str(path))
        module_name = _module_name(root, path)
        classes = {
            node.name: node for node in module.body if isinstance(node, ast.ClassDef)
        }

        for config_node in classes.values():
            if not _has_register_decorator(config_node):
                continue

            model_name = _registered_model_name(config_node)
            model_class = _build_return_class(config_node)
            if model_class not in classes:
                raise ModelDocError(
                    f"{config_node.name}.build returns {model_class!r}, but no "
                    f"class with that name exists in {path}."
                )

            model_node = classes[model_class]
            model_docstring = ast.get_docstring(model_node) or ""
            if not model_docstring.strip():
                raise ModelDocError(f"{module_name}.{model_class} needs a class docstring.")

            docs.append(
                ModelDoc(
                    model_name=model_name,
                    model_class=model_class,
                    model_module=module_name,
                    model_docstring=model_docstring,
                    config_class=config_node.name,
                    config_module=module_name,
                    config_docstring=ast.get_docstring(config_node) or "",
                    config_fields=tuple(_extract_config_fields(config_node)),
                    source_path=path,
                )
            )

    if not docs:
        raise ModelDocError(f"No registered model configs found under {models_dir}.")
    return sorted(docs, key=lambda doc: doc.model_name)


def render_all(model_docs: list[ModelDoc], root: Path = ROOT) -> dict[Path, str]:
    """Render all generated documentation files."""

    output = {
        root / "docs" / "models" / "index.md": render_index(model_docs),
    }
    for model_doc in model_docs:
        output[root / "docs" / "models" / model_doc.page_name] = render_model_page(model_doc)
    return output


def render_index(model_docs: list[ModelDoc]) -> str:
    rows = [
        "| Model | Registry Name | Summary |",
        "| --- | --- | --- |",
    ]
    for model_doc in model_docs:
        rows.append(
            "| "
            f"[{_escape_table(model_doc.model_class)}]({model_doc.page_name}) "
            f"| `{_escape_table(model_doc.model_name)}` "
            f"| {_escape_table(model_doc.summary)} |"
        )

    content = [
        GENERATED_NOTICE,
        "",
        "# Model Documentation",
        "",
        "These pages are generated from registered model config classes, model class "
        "docstrings, and config field defaults.",
        "",
        "After editing a model docstring or config, regenerate these files with:",
        "",
        "```bash",
        "python scripts/generate_model_docs.py",
        "```",
        "",
        *rows,
        "",
    ]
    return "\n".join(content)


def render_model_page(model_doc: ModelDoc) -> str:
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {model_doc.model_class}",
        "",
        model_doc.summary,
        "",
        "## Source",
        "",
        f"- Registry name: `{model_doc.model_name}`",
        f"- Model class: `{model_doc.model_module}.{model_doc.model_class}`",
        f"- Config class: `{model_doc.config_module}.{model_doc.config_class}`",
        f"- Source file: `{model_doc.source_path.relative_to(ROOT)}`",
        "",
    ]

    if model_doc.details:
        lines.extend(
            [
                _rewrite_doc_asset_links(model_doc.details),
                "",
            ]
        )

    config_docstring = model_doc.config_docstring or "No config class docstring is available."
    lines.extend(
        [
            "## Configuration",
            "",
            _rewrite_doc_asset_links(config_docstring),
            "",
            "| Field | Type | Default |",
            "| --- | --- | --- |",
        ]
    )
    for field in model_doc.config_fields:
        lines.append(
            f"| `{_escape_table(field.name)}` "
            f"| `{_escape_table(field.annotation)}` "
            f"| `{_escape_table(field.default)}` |"
        )

    lines.extend(
        [
            "",
            "## Contracts",
            "",
            "- `forward` inputs use `(batch, time, neurons)` observations.",
            "- Runtime outputs follow the [model output contract](../model_output_contract.md).",
            "- Optimizer epochs follow the [optimizer contract](../optimizer_contract.md).",
            "",
        ]
    )
    return "\n".join(lines)


def write_docs(files: dict[Path, str]) -> None:
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def check_docs(files: dict[Path, str]) -> int:
    stale: list[str] = []
    expected_paths = set(files)
    existing_paths = set(MODEL_DOCS_DIR.glob("*.md")) if MODEL_DOCS_DIR.exists() else set()

    for path, expected in files.items():
        if not path.exists() or path.read_text(encoding="utf-8") != expected:
            stale.append(str(path.relative_to(ROOT)))

    extra = sorted(existing_paths - expected_paths)
    if stale or extra:
        if stale:
            print("Stale generated model docs:")
            for path in stale:
                print(f"  {path}")
        if extra:
            print("Unexpected generated model docs:")
            for path in extra:
                print(f"  {path.relative_to(ROOT)}")
        print("Run `python scripts/generate_model_docs.py` to update docs.")
        return 1

    print("Generated model docs are up to date.")
    return 0


def _has_register_decorator(class_node: ast.ClassDef) -> bool:
    for decorator in class_node.decorator_list:
        target = decorator.func if isinstance(decorator, ast.Call) else decorator
        if isinstance(target, ast.Attribute) and target.attr == "register":
            return True
        if isinstance(target, ast.Name) and target.id == "register":
            return True
    return False


def _registered_model_name(class_node: ast.ClassDef) -> str:
    for field in _extract_config_fields(class_node):
        if field.name == "name":
            return field.default.strip("\"'")
    raise ModelDocError(f"{class_node.name} must define a `name` config field.")


def _build_return_class(class_node: ast.ClassDef) -> str:
    for node in class_node.body:
        if isinstance(node, ast.FunctionDef) and node.name == "build":
            if node.returns is None:
                raise ModelDocError(f"{class_node.name}.build needs a return annotation.")
            annotation = _literal_annotation(node.returns)
            if not annotation:
                raise ModelDocError(f"Could not parse {class_node.name}.build return annotation.")
            return annotation.rsplit(".", maxsplit=1)[-1]
    raise ModelDocError(f"{class_node.name} must define a build method.")


def _extract_config_fields(class_node: ast.ClassDef) -> list[ConfigField]:
    fields: list[ConfigField] = []
    for node in class_node.body:
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.target, ast.Name):
            continue
        field_name = node.target.id
        if field_name.startswith("_"):
            continue
        annotation = _node_text(node.annotation)
        if "ClassVar" in annotation:
            continue
        default = _default_text(node.value)
        fields.append(ConfigField(field_name, annotation, default))
    return fields


def _literal_annotation(node: ast.AST) -> str:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    text = _node_text(node)
    return text.strip("\"'")


def _default_text(node: ast.AST | None) -> str:
    if node is None:
        return "<required>"

    if isinstance(node, ast.Call) and _call_name(node.func) == "Field":
        for keyword in node.keywords:
            if keyword.arg == "default":
                return _default_text(keyword.value)
            if keyword.arg == "default_factory" and isinstance(keyword.value, ast.Lambda):
                return _node_text(keyword.value.body)

    text = _node_text(node)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def _call_name(node: ast.AST) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    return ""


def _node_text(node: ast.AST) -> str:
    try:
        return ast.unparse(node)
    except AttributeError as exc:
        raise ModelDocError("Python 3.9+ is required to generate model docs.") from exc


def _module_name(root: Path, path: Path) -> str:
    return ".".join(path.relative_to(root / "src").with_suffix("").parts)


def _first_paragraph(docstring: str) -> str:
    paragraph = docstring.strip().split("\n\n", maxsplit=1)[0]
    return re.sub(r"\s+", " ", paragraph).strip()


def _remaining_docstring(docstring: str) -> str:
    parts = docstring.strip().split("\n\n", maxsplit=1)
    return parts[1].strip() if len(parts) > 1 else ""


def _escape_table(value: str) -> str:
    return value.replace("\n", " ").replace("|", "\\|")


def _rewrite_doc_asset_links(markdown: str) -> str:
    """Resolve docstring asset links from docs/models pages.

    Model docstrings can refer to docs assets with Markdown like
    `![Alt](assets/diagram.png)`. Generated model pages live one directory
    deeper, so those links need to point at `../assets/...`.
    """

    markdown = re.sub(r"(\]\()assets/", r"\1../assets/", markdown)
    markdown = re.sub(r"(<img\b[^>]*\bsrc=[\"'])assets/", r"\1../assets/", markdown)
    return markdown


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated model docs are missing or stale.",
    )
    args = parser.parse_args(argv)

    try:
        model_docs = discover_models(ROOT)
        files = render_all(model_docs, ROOT)
        if args.check:
            return check_docs(files)
        write_docs(files)
    except ModelDocError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote {len(files)} generated model docs under {MODEL_DOCS_DIR.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
